name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jpyke3/mbp-manjaro-linux57
      env: 
        GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
        GPG_KEY: ${{ secrets.GPG_SECRET }}
    steps:
      - run: |
          gpg --import --batch --passphrase $GPG_PASSPHRASE <(echo -e $GPG_KEY);
          makepkg -s --sign
