name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
      env: 
        GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
        GPG_KEY: ${{ secrets.GPG_SECRET }}
    steps:
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg --noconfirm
      - run: useradd -m builder
      - run: su builder
      - run: mkdir -p ~/packages
